baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Gabriel Araujo"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.jpg"
  author = "Gabriel Araujo"
  description = "My personal website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "gabrielaraujof"
  Email         = "contato@gabrielaraujo.dev"
  Twitter       = "gabrielfeear"
  LinkedIn      = "gabrielaraujof"
  Stackoverflow = "gabrielaraujof"
  Medium        = "gabrielaraujof"
  Telegram      = "gabrielaraujof"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/resume/"
